library(exact2x2)
library(effsize)
library(nortest)

setwd("./statistical-analysis/")
data<-read.csv("quality-issues-raw-data.csv")
attach(data)

#Normality tests
ad.test(is_low_quality_DSC_F)
ad.test(is_low_quality_DSC_C)
ad.test(is_low_quality_PTO)
ad.test(is_EM_DSC_C)
ad.test(is_EM_DSC_F)
ad.test(is_EM_PTO)
ad.test(CrystalBLEU_DSC_C)
ad.test(CrystalBLEU_DSC_F)
ad.test(CrystalBLEU_PTO)

#######################################################################################
## RQ2: Comparison of low-quality functions generated by DSC_F and DSC_C             ##
#######################################################################################

res=list(Models=c(),p.value=c(),OR=c())

# low-quality functions Comparison: DSC_C vs DSC_F
mn=mcnemar.exact(is_low_quality_DSC_C, is_low_quality_DSC_F)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_low_quality_DSC_C vs is_low_quality_DSC_F")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# low-quality functions Comparison: DSC_F vs PTO
mn=mcnemar.exact(is_low_quality_DSC_F,is_low_quality_PTO)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_low_quality_DSC_F vs is_low_quality_PTO")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# low-quality functions Comparison: is_low_quality_DSC_C vs is_low_quality_PTO
mn=mcnemar.exact(is_low_quality_DSC_C,is_low_quality_PTO)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_low_quality_DSC_C vs is_low_quality_PTO")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)

# Adjust p-value and print
res$p.value=p.adjust(res$p.value,method = "BH")
print(res)


#######################################################################################
## RQ2: Comparison of syntactically incorrect functions generated by DSC_F and DSC_C ##
#######################################################################################

res=list(Models=c(),p.value=c(),OR=c())

# syntactically incorrect functions Comparison: DSC_C vs DSC_F
mn=mcnemar.exact(is_syn_incorrect_DSC_C, is_syn_incorrect_DSC_F)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_syn_incorrect_DSC_C vs is_syn_incorrect_DSC_F")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# syntactically incorrect functions Comparison: DSC_F vs PTO
mn=mcnemar.exact(is_syn_incorrect_DSC_F,is_syn_incorrect_PTO)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_syn_incorrect_DSC_F vs is_syn_incorrect_PTO")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# syntactically incorrect functions Comparison: DSC_C vs PTO
mn=mcnemar.exact(is_syn_incorrect_DSC_C,is_syn_incorrect_PTO)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_syn_incorrect_DSC_C vs is_syn_incorrect_PTO")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)

# Adjust p-value and print
res$p.value=p.adjust(res$p.value,method = "BH")
print(res)


#######################################################################################
## RQ2: Comparison of performance-related metrics among the three models (EM)        ##
#######################################################################################

res=list(Models=c(),p.value=c(),OR=c())

# EM Comparison: DSC_C vs DSC_F
mn=mcnemar.exact(is_EM_DSC_C, is_EM_DSC_F)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_EM_DSC_C vs is_EM_DSC_F")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# EM Comparison: PTO vs DSC_F
mn=mcnemar.exact(is_EM_PTO,is_EM_DSC_F)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_EM_PTO vs is_EM_DSC_F")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# EM Comparison: PTO vs DSC_C
mn=mcnemar.exact(is_EM_PTO, is_EM_DSC_C)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"is_EM_PTO vs is_EM_DSC_C")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)

# Adjust p-value and print
res$p.value=p.adjust(res$p.value,method = "BH")
print(res)



#########################################################################################
## RQ2: Comparison of performance-related metrics among the three models (Crystal BLEU) #
#########################################################################################

res=list(Models=c(),p.value=c(),cliff=c())

# Crystal BLEU Comparison: DSC_C vs DSC_F
p.value=wilcox.test(CrystalBLEU_DSC_C, CrystalBLEU_DSC_F, paired=TRUE)$p.value
cliff=cliff.delta(CrystalBLEU_DSC_C, CrystalBLEU_DSC_F, paired=TRUE)

res$Models=c(res$Models,"CrystalBLEU_DSC_C vs CrystalBLEU_DSC_F")
res$p.value=c(res$p.value,p.value)
res$cliff=c(res$cliff,cliff)


# Crystal BLEU Comparison: PTO vs DSC_F
p.value=wilcox.test(CrystalBLEU_PTO, CrystalBLEU_DSC_F, paired=TRUE)$p.value
cliff=cliff.delta(CrystalBLEU_PTO, CrystalBLEU_DSC_F, paired=TRUE)

res$Models=c(res$Models,"CrystalBLEU_PTO vs CrystalBLEU_DSC_F")
res$p.value=c(res$p.value,p.value)
res$cliff=c(res$cliff,cliff)


# Crystal BLEU Comparison: PTO vs DSC_C
p.value=wilcox.test(CrystalBLEU_PTO, CrystalBLEU_DSC_C, paired=TRUE)$p.value
cliff=cliff.delta(CrystalBLEU_PTO, CrystalBLEU_DSC_C, paired=TRUE)

res$Models=c(res$Models,"CrystalBLEU_PTO vs CrystalBLEU_DSC_C")
res$p.value=c(res$p.value,p.value)
res$cliff=c(res$cliff,cliff)

# Adjust p-value and print
res$p.value=p.adjust(res$p.value,method = "BH")
print(res)


################################################################################################
## RQ2: Comparison of performance-related metrics among the three models (pass@1 on HumanEval) #
################################################################################################

human_eval<-read.csv("humaneval-raw-data.csv")
attach(human_eval)

#Normality tests
ad.test(HumanEval_F)
ad.test(HumanEval_C)
ad.test(HumanEval_PTO)

res=list(Models=c(),p.value=c(),OR=c())

# pass@1 Comparison: DSC_C vs DSC_F
mn=mcnemar.exact(HumanEval_C, HumanEval_F)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"HumanEval_C vs HumanEval_F")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# pass@1 Comparison: PTO vs DSC_F
mn=mcnemar.exact(HumanEval_PTO,HumanEval_F)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"HumanEval_PTO vs HumanEval_F")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)


# pass@1 Comparison: PTO vs DSC_C
mn=mcnemar.exact(HumanEval_PTO, HumanEval_C)
p.value=mn$p.value
or=mn$estimate

res$Models=c(res$Models,"HumanEval_PTO vs HumanEval_C")
res$p.value=c(res$p.value,p.value)
res$OR=c(res$OR,or)

# Adjust p-value and print
res$p.value=p.adjust(res$p.value,method = "BH")
print(res)